### ISSUE TITLE
With 01.0 release - exception on line 4 of raml-client.js

### ISSUE THREAD

**Issue by nmunro-cvt** [mulesoft/raml-client-generator#18]
JS client is generated cleanly in version 0.0.7 but with 0.1.0 I get error

>$ raml-to-client api.raml -o api-client -l javascript
>module.js:338
>    throw err;
>          ^
>Error: Cannot find module '../'
>    at Function.Module._resolveFilename (module.js:336:15)
>    at Function.Module._load (module.js:278:25)
>    at Module.require (module.js:365:17)
>    at require (module.js:384:17)
>    at Object.<anonymous> (/usr/local/lib/node_modules/raml-client-generator/bin/raml-client.js:4:17)
>    at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Function.Module.runMain (module.js:501:10)
>$

Seems to happen on this line in raml-client.js
> var languages = require('../')

so I don't think it has anything to do with my RAML

**Comment by blakeembrey** [comment]
You're correct, it's not. My fault, I'll release a patch for you right now :+1:

**Comment by blakeembrey** [comment]
Released with `0.1.1`.
