### ISSUE TITLE
Language Implementation

### ISSUE THREAD

**Issue by WenTingZhu** [mulesoft/raml-client-generator#19]
There have been a lot of structural changes in the raml-client-generator, but the language implementation guide is out of date.

**Comment by blakeembrey** [comment]
You're right, thanks for bringing it up :+1: I'll be sure to update it ASAP.

**Comment by blakeembrey** [comment]
Replaced it with https://github.com/mulesoft/raml-client-generator/blob/master/IMPLEMENTATION.md#creating-new-clients. It's not super in-depth, but hopefully the `raml-generator` project will be improved as questions come up. Thanks again!

**Comment by WenTingZhu** [comment]
Do you have any suggestions on how to write tests for a client that is not in javascript? Thanks.

**Comment by blakeembrey** [comment]
@WenTingZhu You should be able to write tests in whatever language framework is normal for you. Just set up the client and make API calls to a mock server that has a corresponding RAML document (that server could be a mock itself using something like https://github.com/mulesoft-labs/osprey-mock-service).
