### ISSUE TITLE
query parameters on PUT, POST

### ISSUE THREAD

**Issue by mjasinski5** [mulesoft/raml-client-generator#20]
Hello folks!

First things first, you did really great job there. App is amazing and well built.. but only one thing bothers me... : 
Im afraid support for POST, PUT query parameters is missing.. Do you have any plans to add this functionality? Its kind of important feature as every complex API has such needs ;)

Cheers,
  Mariusz

**Comment by blakeembrey** [comment]
@mjasinski5 Query parameters should be working, but they are passed as the second argument for non-GET requests. For example, `post(null, { query: { foo: 'bar' } })`. Please let me know if that doesn't work for you :smile:

**Comment by mjasinski5** [comment]
Yea it works! Great :) Thanks for help, you saved my time, I wanted to write it on my own^^

**Comment by blakeembrey** [comment]
Great! I'm going to close the issue, but let me know if you have any other issues. Did the documentation (README) not get generated with help for `query`?

**Comment by mjasinski5** [comment]
Yea it was the problem :( Im using apinoteebook and there wasn't any information about that + I searched also at official documentation and there was only information about query parameters for GET.
