### ISSUE TITLE
Error fetching file

### ISSUE THREAD

**Issue by emanuelef** [mulesoft/raml-client-generator#6]
Hi,
I'm trying to generate the client code for a RAML file but I get an error when fetching the file.
Is Windows supported ? In my RAML I included external JSON files using !import, could this be the problem?
Thanks in advance

C:\Users\fumagale\workspace\testGen>raml-to-client vsoapiNextGenLight.raml -o ap
i-client -l javascript
cannot fetch C:\Users\fumagale\workspace\testGen\vsoapiNextGenLight.raml (while
reading C:\Users\fumagale\workspace\testGen\vsoapiNextGenLight.raml
unknown protocol c:)

**Comment by blakeembrey** [comment]
Updated in the latest version :smile:
